import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from mnist_classifier.classifier_interface import MnistClassifierInterface
from tensorflow.keras.callbacks import EarlyStopping
class CNNModel(MnistClassifierInterface):
    """
    The implemented model is a Convolutional Neural Network specifically optimized for the classification of grayscale handwritten digits.
    The architecture follows a sequential design composed of two main stages: hierarchical feature extraction and classification.
    The feature extraction phase utilizes two convolutional blocks; the first block applies 32 filters with a 3x3 kernel size to capture
    low-level geometric features, while the second block expands the depth to 64 filters to identify more complex patterns.
    Each convolutional operation is followed by a 2x2 Max Pooling layer for spatial dimensionality reduction and a
    Dropout layer (rate 0.25) to mitigate overfitting during the learning process. Following the feature extraction,
    the resulting 3D feature maps are flattened into a 1D vector and passed through a densely connected classifier.
    This section incorporates a high-rate Dropout layer (0.5) to ensure robust generalization, followed by a hidden fully connected
    layer with 128 units using ReLU activation. The final prediction is generated by a Softmax output layer that produces a probability distribution across the
    10 target classes, with the entire network optimized using the Adam algorithm and sparse categorical cross-entropy loss function.
    """
    def __init__(self):
        self.model = keras.Sequential([
            layers.Input(shape=(28, 28)),
            layers.Reshape((28, 28, 1)),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Dropout(0.25),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Dropout(0.25),
            layers.Flatten(),
            layers.Dropout(0.5),
            keras.layers.Dense(128, activation='relu'),
            keras.layers.Dense(10, activation='softmax')
        ])

        self.model.compile(optimizer=keras.optimizers.Adam(learning_rate=1e-3),
                           loss='sparse_categorical_crossentropy',
                           metrics=['accuracy'])

    def train(self, X_train, y_train, X_val=None, y_val=None):
        val_data = (X_val, y_val) if X_val is not None else None
        early_stopping = EarlyStopping(
            monitor='val_loss',
            patience=3,
            restore_best_weights=True
        )
        history = self.model.fit(
            X_train, y_train,
            epochs=10,
            batch_size=32,
            verbose=1,
            validation_data=val_data,
            callbacks = [early_stopping]
        )
        self.model.fit(X_train, y_train, epochs=5, batch_size=32)
        return history.history

    def predict(self, X_test):
        predictions = self.model.predict(X_test)
        return np.argmax(predictions, axis=1)